version: "3.8"

services:

  producer:
    build: ./producer
    container_name: producer
    restart: always
    env_file:
      - .env
    depends_on:
      - processor

  processor:
    build: ./log_processor
    container_name: processor
    restart: always
    env_file:
      - .env

  api:
    build: ./incident_service
    container_name: api
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
